# Generated by Django 5.2.17 on 2026-10-03 01:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_migrate_statuses'),
        ('jobs', '0004_joboffer_fields_savedjob_jobalert_jobofferview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='réponse')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Test technique', max_length=150, verbose_name='titre')),
                ('instructions', models.TextField(blank=True, verbose_name='consignes')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='durée (minutes)')),
                ('is_active', models.BooleanField(default=True, help_text='Les candidats doivent passer le test après avoir postulé.', verbose_name='actif')),
                ('job_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'QCM',
                'verbose_name_plural': 'QCM',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='score (%)')),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('timed_out', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt', to='applications.application')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.quizattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='one_answer_per_question')],
            },
        ),
    ]
