# Generated by Django 5.2.17 on 2026-09-12 10:37

import accounts.models
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, help_text='CV au format PDF uniquement', null=True, upload_to=accounts.models.candidate_cv_upload_path, validators=[accounts.validators.validate_pdf_file]),
        ),
    ]
