# Generated by Django 5.2.17 on 2026-10-03 01:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_candidate_sections_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, help_text='CV au format PDF uniquement', null=True, upload_to=accounts.models.candidate_cv_upload_path, validators=[accounts.models.validate_cv_file]),
        ),
    ]
